server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Polaroid?serverTimezone=Asia/Seoul
    username: bigDreamTree
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: polaroid0325@gmail.com
    password: polaroid123
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 1006646380284-452sgmdlq7f8dfo6usqphcb7esioaelg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 972911066688447
            client-secret: 12049f667e86cbae79b70643d9d2b905
            scope:
              - email
              - public_profile

          naver:
            client-id: 8V6me7cR8darm_GNLHfo
            client-secret: fH6gBe5efQ
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/naver

          kakao:
            client-id: 45536e3c56f87bddc4ecfe3b5ad099c3
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response